/*
 * @generated by Linden. DO NOT EDIT.
 * systemId: 7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314
 * packageScope: @linden
 * contractId: component.button
 * schemaVersion: 1
 * contractRevision: sha256:e16940129c03575bb21ee03b7fdafe37c094ffd8188c3d1d4af5033fceb86dae
 * generatorVersion: 0.1.0
 */

const documentation = {
  "accessibility": {
    "allowsIconOnly": false,
    "allowsVisuallyHiddenLabelWhileLoading": true,
    "focusIndicatorRequired": true,
    "keyboardActivation": "platform-standard",
    "loadingBusyStateRequired": true,
    "requiresAccessibleName": true,
    "requiresVisibleLabel": true
  },
  "anatomy": {
    "label": {
      "required": true
    },
    "leadingIcon": {
      "required": false
    },
    "leadingIconKeyline": {
      "required": true
    },
    "loadingIndicator": {
      "required": true
    },
    "loadingIndicatorKeyline": {
      "required": true
    },
    "root": {
      "required": true
    },
    "trailingIcon": {
      "required": false
    },
    "trailingIconKeyline": {
      "required": true
    }
  },
  "behavior": {
    "action": "triggers-action",
    "activation": "platform-standard",
    "disabled": {
      "interactionDisabled": true
    },
    "focus": {
      "visibleOnKeyboard": true
    },
    "loading": {
      "accessibleNamePreserved": true,
      "busyStateExposed": true,
      "contentVisuallyHidden": true,
      "indicator": "foundation.icons.icon.loader-circle",
      "indicatorCenteredOutsideFlow": true,
      "indicatorDecorative": true,
      "interactionDisabled": true,
      "layoutSizePreserved": true,
      "reducedMotion": "static"
    }
  },
  "discovery": {
    "intents": [
      "submit",
      "confirm",
      "trigger-action",
      "destructive-action"
    ]
  },
  "examples": [
    {
      "intent": "submit",
      "label": "Submit",
      "variant": "primary"
    },
    {
      "intent": "confirm",
      "label": "Confirm",
      "variant": "secondary"
    },
    {
      "intent": "trigger-action",
      "label": "Refresh",
      "variant": "tertiary"
    },
    {
      "intent": "destructive-action",
      "label": "Delete",
      "variant": "danger"
    }
  ],
  "guidance": {
    "avoidWhen": "Use Link for navigation.",
    "content": {
      "donts": [
        "Do not use vague labels.",
        "Do not use an icon-only label."
      ],
      "dos": [
        "Use a concise verb label.",
        "Keep the label stable during loading."
      ]
    },
    "examples": [
      {
        "intent": "submit",
        "label": "Submit",
        "variant": "primary"
      },
      {
        "intent": "confirm",
        "label": "Confirm",
        "variant": "secondary"
      },
      {
        "intent": "trigger-action",
        "label": "Refresh",
        "variant": "tertiary"
      },
      {
        "intent": "destructive-action",
        "label": "Delete",
        "variant": "danger"
      }
    ],
    "purpose": "Triggers an action.",
    "useWhen": "Use for a concise user action."
  },
  "id": "component.button",
  "kind": "component-documentation",
  "props": {
    "disabled": {
      "kind": "boolean",
      "required": false
    },
    "label": {
      "kind": "text",
      "required": true
    },
    "leadingIcon": {
      "kind": "icon",
      "required": false
    },
    "loading": {
      "kind": "boolean",
      "required": false
    },
    "size": {
      "kind": "choice",
      "required": false,
      "values": [
        "small",
        "medium",
        "large"
      ]
    },
    "trailingIcon": {
      "kind": "icon",
      "required": false
    },
    "variant": {
      "kind": "choice",
      "required": false,
      "values": [
        "primary",
        "secondary",
        "tertiary",
        "danger"
      ]
    }
  },
  "provenance": {
    "contractId": "component.button",
    "contractRevision": "sha256:e16940129c03575bb21ee03b7fdafe37c094ffd8188c3d1d4af5033fceb86dae",
    "generatorVersion": "0.1.0",
    "packageScope": "@linden",
    "schemaVersion": 1,
    "systemId": "7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314"
  },
  "purpose": "Triggers an action.",
  "relationships": {
    "relatedComponents": [
      "link"
    ]
  },
  "revision": "sha256:e16940129c03575bb21ee03b7fdafe37c094ffd8188c3d1d4af5033fceb86dae",
  "schemaVersion": 1,
  "styling": {
    "disabled": {
      "opacity": "foundation.tokens.opacity.base.50"
    },
    "focus": {
      "cornerRadius": "foundation.tokens.dimension.3-5",
      "outlineColor": "foundation.tokens.color.state.focused",
      "outlineOffset": "foundation.tokens.focus-ring.offset-md",
      "outlineWidth": "foundation.tokens.border-width.4"
    },
    "loading": {
      "duration": "foundation.tokens.motion.duration.loading-spinner"
    },
    "shared": {
      "borderWidth": "foundation.tokens.border-width.1",
      "cornerRadius": "foundation.tokens.radius.lg",
      "fontFamily": "foundation.tokens.family.control.default",
      "fontStyle": "foundation.tokens.style.control.default"
    },
    "sizes": {
      "large": {
        "fontSize": "foundation.tokens.size.control.md",
        "fontWeight": "foundation.tokens.weight.control.default",
        "gap": "foundation.tokens.gap.2",
        "height": "foundation.tokens.dimension.12",
        "keyline": "foundation.tokens.dimension.6",
        "letterSpacing": "foundation.tokens.tracking.control.md",
        "lineHeight": "foundation.tokens.leading.control.md",
        "paddingInline": "foundation.tokens.padding.6"
      },
      "medium": {
        "fontSize": "foundation.tokens.size.control.md",
        "fontWeight": "foundation.tokens.weight.control.default",
        "gap": "foundation.tokens.gap.2",
        "height": "foundation.tokens.dimension.11",
        "keyline": "foundation.tokens.dimension.5",
        "letterSpacing": "foundation.tokens.tracking.control.md",
        "lineHeight": "foundation.tokens.leading.control.md",
        "paddingInline": "foundation.tokens.padding.4"
      },
      "small": {
        "fontSize": "foundation.tokens.size.control.md",
        "fontWeight": "foundation.tokens.weight.control.default",
        "gap": "foundation.tokens.gap.1-5",
        "height": "foundation.tokens.dimension.10",
        "keyline": "foundation.tokens.dimension.4",
        "letterSpacing": "foundation.tokens.tracking.control.md",
        "lineHeight": "foundation.tokens.leading.control.md",
        "paddingInline": "foundation.tokens.padding.3"
      }
    },
    "variants": {
      "danger": {
        "hover": {
          "border": "foundation.tokens.color.fill.danger-hover",
          "fill": "foundation.tokens.color.fill.danger-hover",
          "text": "foundation.tokens.color.text.on-danger"
        },
        "pressed": {
          "border": "foundation.tokens.color.fill.danger-pressed",
          "fill": "foundation.tokens.color.fill.danger-pressed",
          "text": "foundation.tokens.color.text.on-danger"
        },
        "rest": {
          "border": "foundation.tokens.color.border.danger",
          "fill": "foundation.tokens.color.fill.danger",
          "text": "foundation.tokens.color.text.on-danger"
        }
      },
      "primary": {
        "hover": {
          "border": "foundation.tokens.color.fill.primary-hover",
          "fill": "foundation.tokens.color.fill.primary-hover",
          "text": "foundation.tokens.color.text.on-primary"
        },
        "pressed": {
          "border": "foundation.tokens.color.fill.primary-pressed",
          "fill": "foundation.tokens.color.fill.primary-pressed",
          "text": "foundation.tokens.color.text.on-primary"
        },
        "rest": {
          "border": "foundation.tokens.color.border.primary",
          "fill": "foundation.tokens.color.fill.primary",
          "text": "foundation.tokens.color.text.on-primary"
        }
      },
      "secondary": {
        "hover": {
          "border": "foundation.tokens.color.border.secondary",
          "fill": "foundation.tokens.color.fill.secondary-hover",
          "text": "foundation.tokens.color.text.on-secondary"
        },
        "pressed": {
          "border": "foundation.tokens.color.border.secondary",
          "fill": "foundation.tokens.color.fill.secondary-pressed",
          "text": "foundation.tokens.color.text.on-secondary"
        },
        "rest": {
          "border": "foundation.tokens.color.border.secondary",
          "fill": "foundation.tokens.color.fill.secondary",
          "text": "foundation.tokens.color.text.on-secondary"
        }
      },
      "tertiary": {
        "hover": {
          "border": "foundation.tokens.color.border.tertiary",
          "fill": "foundation.tokens.color.fill.tertiary-hover",
          "text": "foundation.tokens.color.text.primary"
        },
        "pressed": {
          "border": "foundation.tokens.color.border.tertiary",
          "fill": "foundation.tokens.color.fill.tertiary-pressed",
          "text": "foundation.tokens.color.text.primary"
        },
        "rest": {
          "border": "foundation.tokens.color.border.tertiary",
          "fill": "foundation.tokens.color.fill.tertiary",
          "text": "foundation.tokens.color.text.primary"
        }
      }
    }
  }
};
const provenance = documentation.provenance;

export { documentation, provenance };
export default documentation;
