// @generated by Linden. DO NOT EDIT.
// systemId: 7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314
// packageScope: @linden
// contractId: component.button
// schemaVersion: 1
// contractRevision: sha256:e16940129c03575bb21ee03b7fdafe37c094ffd8188c3d1d4af5033fceb86dae
// generatorVersion: 0.1.0
import type { ButtonHTMLAttributes, ReactNode } from "react";
import { LoaderCircleIcon } from "@linden/icons";
import "./Button.css";

export type ButtonVariant = "primary" | "secondary" | "tertiary" | "danger";
export type ButtonSize = "small" | "medium" | "large";

export type ButtonProps = Omit<ButtonHTMLAttributes<HTMLButtonElement>, "children" | "disabled" | "style"> & {
  label: string;
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  disabled?: boolean;
  leadingIcon?: ReactNode;
  trailingIcon?: ReactNode;
};

export function Button({ label, variant = "primary", size = "medium", loading = false, disabled = false, leadingIcon, trailingIcon, type = "button", className, ...buttonProps }: ButtonProps) {
  if (!label.trim()) throw new TypeError("Button label must not be blank");
  const isDisabled = disabled || loading;
  return (
    <button {...buttonProps} type={type} className={["linden-button", className].filter(Boolean).join(" ")} disabled={isDisabled} aria-busy={loading || undefined} data-variant={variant} data-size={size} data-loading={loading ? "true" : "false"}>
      <span data-part="leading-icon-keyline" data-visible={leadingIcon ? "true" : "false"} aria-hidden="true">{leadingIcon ? <span data-part="leading-icon">{leadingIcon}</span> : null}</span>
      <span data-part="label">{label}</span>
      <span data-part="trailing-icon-keyline" data-visible={trailingIcon ? "true" : "false"} aria-hidden="true">{trailingIcon ? <span data-part="trailing-icon">{trailingIcon}</span> : null}</span>
      <span data-part="loading-indicator-keyline" aria-hidden="true"><span data-part="loading-indicator"><LoaderCircleIcon /></span></span>
    </button>
  );
}
