// @generated by Linden. DO NOT EDIT.
// systemId: 7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314
// packageScope: @linden
// contractId: component.button
// schemaVersion: 1
// contractRevision: sha256:e16940129c03575bb21ee03b7fdafe37c094ffd8188c3d1d4af5033fceb86dae
// generatorVersion: 0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { Button } from "./Button.tsx";
import { buttonContract } from "./Button.contract.ts";

describe("Button contract conformance", () => {
  it("projects contract defaults", () => {
    render(<Button label="Save" />);
    const control = screen.getByRole("button", { name: "Save" });
    expect(control).toHaveAttribute("data-variant", "primary");
    expect(control).toHaveAttribute("data-size", "medium");
    expect(control).toBeEnabled();
  });

  it("covers every declared variant and size", () => {
    expect(Object.keys(buttonContract.styling.variants).sort()).toEqual([
  "danger",
  "primary",
  "secondary",
  "tertiary"
]);
    expect(Object.keys(buttonContract.styling.sizes).sort()).toEqual([
  "large",
  "medium",
  "small"
]);
  });

  it("projects loading through native disabled and aria-busy", () => {
    render(<Button label="Save" loading />);
    const control = screen.getByRole("button", { name: "Save" });
    expect(control).toBeDisabled();
    expect(control).toHaveAttribute("aria-busy", "true");
    expect(control).toHaveAccessibleName("Save");
    expect(control.querySelector('[data-part="label"]')).toHaveTextContent("Save");
    expect(control.querySelector('[data-part="loading-indicator-keyline"]')).toHaveAttribute("aria-hidden", "true");
    expect(control.querySelector('[data-part="loading-indicator"]')).toBeInTheDocument();
  });

  it("keeps all keylines in the DOM", () => {
    render(<Button label="Save" />);
    const control = screen.getByRole("button", { name: "Save" });
    expect(control.querySelector('[data-part="leading-icon-keyline"]')).toHaveAttribute("data-visible", "false");
    expect(control.querySelector('[data-part="trailing-icon-keyline"]')).toHaveAttribute("data-visible", "false");
    expect(control.querySelector('[data-part="loading-indicator-keyline"]')).toBeInTheDocument();
  });

  it("projects disabled through the native disabled attribute", () => {
    render(<Button label="Save" disabled />);
    expect(screen.getByRole("button", { name: "Save" })).toBeDisabled();
  });
});
