// @generated by Linden. DO NOT EDIT.
// systemId: 7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314
// packageScope: @linden
// contractId: component.button
// schemaVersion: 1
// contractRevision: sha256:e16940129c03575bb21ee03b7fdafe37c094ffd8188c3d1d4af5033fceb86dae
// generatorVersion: 0.1.0
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button } from "./Button.tsx";

const meta = { title: "Components/Button", component: Button, parameters: { layout: "centered" }, args: {
  "disabled": false,
  "label": "Submit",
  "loading": false,
  "size": "medium",
  "variant": "primary"
} } satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const Submit: Story = { args: {
  "label": "Submit",
  "variant": "primary"
} };

export const Confirm: Story = { args: {
  "label": "Confirm",
  "variant": "secondary"
} };

export const TriggerAction: Story = { args: {
  "label": "Refresh",
  "variant": "tertiary"
} };

export const DestructiveAction: Story = { args: {
  "label": "Delete",
  "variant": "danger"
} };

export const VariantPrimary: Story = { args: { variant: "primary" } };

export const VariantSecondary: Story = { args: { variant: "secondary" } };

export const VariantTertiary: Story = { args: { variant: "tertiary" } };

export const VariantDanger: Story = { args: { variant: "danger" } };

export const SizeSmall: Story = { args: { size: "small" } };

export const SizeMedium: Story = { args: { size: "medium" } };

export const SizeLarge: Story = { args: { size: "large" } };

export const Loading: Story = { args: { loading: true } };
export const Disabled: Story = { args: { disabled: true } };
