import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import { buttonContract } from "../../components/Button/Button.contract.ts";
// @ts-expect-error The imported generated documentation is a runtime artifact without authored types.
import { documentation, provenance } from "../../components/Button/Button.doc.mjs";
import { tokensContract } from "../../foundations/tokens/Tokens.contract.ts";
import { generateComponentOutputs } from "../../generators/component.ts";
import { contractRevision, GENERATOR_VERSION, writeArtifacts } from "../../generators/core.ts";
import { renderAll } from "../../generators/generate.ts";
import { defineSystemConfig, systemConfig } from "../../system.config.ts";

const root = resolve(import.meta.dirname, "../..");
const read = (path: string) => readFileSync(resolve(root, path), "utf8");
const buttonRevision = contractRevision(buttonContract);
const tokenRevision = contractRevision(tokensContract);

const buttonHeader = {
  "systemId": systemConfig.systemId,
  "packageScope": systemConfig.packageScope,
  "contractId": buttonContract.id,
  "schemaVersion": String(buttonContract.schemaVersion),
  "contractRevision": buttonRevision,
  "generatorVersion": GENERATOR_VERSION,
};
const tokensHeader = {
  ...buttonHeader,
  "contractId": "foundation.tokens",
  "schemaVersion": String(tokensContract.schemaVersion),
  "contractRevision": tokenRevision,
};

function expectHeader(source: string, metadata: Record<string, string>): void {
  expect(source).toContain(`@generated by ${systemConfig.displayName}. DO NOT EDIT.`);
  for (const [key, value] of Object.entries(metadata)) expect(source).toContain(`${key}: ${value}`);
}

function collectTokenReferences(value: unknown, references = new Set<string>()): Set<string> {
  if (typeof value === "string" && value.startsWith("foundation.tokens.")) references.add(value);
  else if (Array.isArray(value)) value.forEach((child) => collectTokenReferences(child, references));
  else if (value && typeof value === "object") Object.values(value).forEach((child) => collectTokenReferences(child, references));
  return references;
}

function reverseObjectKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(reverseObjectKeys);
  if (value && typeof value === "object" && Object.getPrototypeOf(value) === Object.prototype) {
    return Object.fromEntries(Object.entries(value).reverse().map(([key, child]) => [key, reverseObjectKeys(child)]));
  }
  return value;
}

describe("generated Button golden artifacts", () => {
  it("pins immutable system identity and renders the exact deterministic artifact set", () => {
    expect(systemConfig.systemId).toBe("7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314");
    expect(Object.isFrozen(systemConfig)).toBe(true);
    expect(Object.isFrozen(systemConfig.packages)).toBe(true);

    const expectedPaths = [
      "foundations/tokens/Tokens.css",
      "foundations/tokens/Tokens.ts",
      "foundations/tokens/Tokens.doc.mjs",
      "foundations/assets/Icons.ts",
      "foundations/assets/Icons.doc.mjs",
      "foundations/assets/Fonts.css",
      "components/Button/Button.tsx",
      "components/Button/Button.css",
      "components/Button/Button.test.tsx",
      "components/Button/Button.stories.tsx",
      "components/Button/Button.doc.mjs",
    ];
    const first = renderAll();
    const second = renderAll();
    expect(first.map(({ path }) => path)).toEqual(expectedPaths);
    expect(second).toEqual(first);
  });

  it("keeps every generated byte stable for semantically equivalent field order", () => {
    const reordered = {
      ...buttonContract,
      behavior: reverseObjectKeys(buttonContract.behavior),
      accessibility: reverseObjectKeys(buttonContract.accessibility),
      styling: {
        ...buttonContract.styling,
        variants: reverseObjectKeys(buttonContract.styling.variants),
        sizes: reverseObjectKeys(buttonContract.styling.sizes),
      },
    } as typeof buttonContract;
    expect(generateComponentOutputs(reordered, systemConfig)).toEqual(generateComponentOutputs(buttonContract, systemConfig));
  });

  it("rejects layered interaction states", () => {
    const layered = {
      ...buttonContract,
      styling: {
        ...buttonContract.styling,
        variants: {
          ...buttonContract.styling.variants,
          primary: {
            ...buttonContract.styling.variants.primary,
            hover: {
              ...buttonContract.styling.variants.primary.hover,
              overlay: "foundation.tokens.color.fill.primary",
            },
          },
        },
      },
    } as unknown as typeof buttonContract;
    expect(() => generateComponentOutputs(layered, systemConfig)).toThrow(
      "component.styling.variants.primary.hover has unsupported fields",
    );
  });

  it("projects the configured icon package into generated Button imports", () => {
    const customConfig = defineSystemConfig({
      ...systemConfig,
      packageScope: "@other",
      packages: { ...systemConfig.packages, icons: "symbols" },
    });
    const source = generateComponentOutputs(buttonContract, customConfig).find(({ path }) => path.endsWith(".tsx"))?.contents;
    expect(source).toContain('import { LoaderCircleIcon } from "@other/symbols";');
    expect(source).toContain('className={["other-button", className].filter(Boolean).join(" ")}');
  });

  it("rejects every output path before writing any artifact", () => {
    const tempRoot = mkdtempSync(resolve(tmpdir(), "linden-writer-"));
    const outputs = [
      { path: "valid.txt", contents: "valid" },
      { path: "../escape.txt", contents: "invalid" },
    ];
    try {
      expect(() => writeArtifacts(tempRoot, outputs)).toThrow(/artifact escapes root/);
      expect(() => writeArtifacts(tempRoot, outputs, true)).toThrow(/artifact escapes root/);
      expect(() => readFileSync(resolve(tempRoot, "valid.txt"), "utf8")).toThrow();
    } finally {
      rmSync(tempRoot, { recursive: true, force: true });
    }
  });

  it("requires explicit overwrite approval for every existing generated diff", () => {
    const tempRoot = mkdtempSync(resolve(tmpdir(), "linden-writer-provenance-"));
    const output = renderAll().find(({ path }) => path === "components/Button/Button.tsx")!;
    const target = resolve(tempRoot, output.path);
    mkdirSync(resolve(target, ".."), { recursive: true });
    try {
      writeFileSync(target, `${output.contents}\nmanual edit\n`, "utf8");
      expect(() => writeArtifacts(tempRoot, [output])).toThrow(/without explicit --force/);
      expect(readFileSync(target, "utf8")).toContain("manual edit");

      const nextRevision = `sha256:${"0".repeat(64)}`;
      const reviewedOutput = { ...output, contents: output.contents.replaceAll(buttonRevision, nextRevision) };
      expect(() => writeArtifacts(tempRoot, [reviewedOutput])).toThrow(/without explicit --force/);
      writeArtifacts(tempRoot, [reviewedOutput], false, true);
      expect(readFileSync(target, "utf8")).toBe(reviewedOutput.contents);
    } finally {
      rmSync(tempRoot, { recursive: true, force: true });
    }
  });

  it("preserves provenance across generated Button and token artifacts", async () => {
    const files = [
      ["components/Button/Button.tsx", buttonHeader],
      ["components/Button/Button.css", buttonHeader],
      ["components/Button/Button.doc.mjs", buttonHeader],
      ["foundations/tokens/Tokens.css", tokensHeader],
      ["foundations/tokens/Tokens.ts", tokensHeader],
      ["foundations/tokens/Tokens.doc.mjs", tokensHeader],
    ] as const;
    for (const [path, metadata] of files) expectHeader(read(path), metadata);

    expect(documentation.id).toBe(buttonContract.id);
    expect(documentation.revision).toBe(buttonRevision);
    expect(documentation.schemaVersion).toBe(buttonContract.schemaVersion);
    expect(provenance).toEqual({ ...buttonHeader, schemaVersion: buttonContract.schemaVersion });
  });

  it("binds every declared Button style token to a used Linden CSS variable", () => {
    const tokensCss = read("foundations/tokens/Tokens.css");
    const buttonCss = read("components/Button/Button.css");
    for (const reference of collectTokenReferences(buttonContract.styling)) {
      const variable = `--${systemConfig.packageScope.slice(1)}-${reference.slice("foundation.tokens.".length).replaceAll(".", "-")}`;
      expect(tokensCss).toMatch(new RegExp(`${variable.replaceAll("-", "\\-")}\\s*:`));
      expect(buttonCss).toContain(`var(${variable})`);
    }
    const prefix = systemConfig.packageScope.slice(1);
    expect(tokensCss).toContain(`--${prefix}-color-border-primary: var(--${prefix}-color-fill-primary);`);
    expect(buttonCss).toContain(`border-color: var(--${prefix}-color-border-primary);`);
  });

  it("keeps focus and direct interaction-state fill CSS contracts intact", () => {
    const css = read("components/Button/Button.css");
    const selector = `\\.${systemConfig.packageScope.slice(1)}-button`;
    expect(css).toMatch(new RegExp(`${selector}:focus-visible\\s*\\{`));
    expect(css).toMatch(new RegExp(`${selector}:focus-visible::after\\s*\\{`));
    expect(css).toContain("outline: none;");
    expect(css).not.toContain("::before");
    expect(css).not.toContain("isolation: isolate");
    expect(css).not.toContain("color-overlay");
    expect(css).toContain("background: var(--linden-color-fill-primary-hover);");
    expect(css).toContain("background: var(--linden-color-fill-primary-pressed);");
    for (const selector of css.matchAll(/([^{}]+):hover\s*\{/g)) expect(selector[1]).toContain(":not(:disabled)");
  });

  it("projects persistent token-sized keylines and reduced loading motion", () => {
    const source = read("components/Button/Button.tsx");
    const css = read("components/Button/Button.css");
    for (const part of ["leading-icon-keyline", "trailing-icon-keyline", "loading-indicator-keyline"]) {
      expect(source).toContain(`data-part="${part}"`);
    }
    expect(source).toContain('import { LoaderCircleIcon } from "@linden/icons";');
    expect(css).toContain('[data-part$="keyline"][data-visible="false"]');
    expect(css).toContain('[data-part="leading-icon"] > *');
    expect(css).toContain('[data-part="trailing-icon"] > *');
    expect(css).toContain('[data-part="loading-indicator"] > *');
    expect(css).toMatch(/\[data-part="leading-icon"\] > \*[\s\S]*?inline-size: 100%;[\s\S]*?block-size: 100%;[\s\S]*?color: inherit;/);
    expect(css).toContain('[data-loading="true"] > [data-part="label"]');
    expect(css).toContain("opacity: 0;");
    expect(css).toContain("var(--linden-motion-duration-loading-spinner) linear infinite");
    expect(css).toContain("@media (prefers-reduced-motion: reduce)");
    for (const step of ["4", "5", "6"]) expect(css).toContain(`var(--linden-dimension-${step})`);
  });

  it("keeps generator output generic", () => {
    const source = ["generators/core.ts", "generators/component.ts", "generators/tokens.ts", "generators/generate.ts"].map(read).join("\n");
    expect(source).not.toContain("component.button");
    expect(source).not.toContain("ButtonAdapter");
  });
});
