// @generated by Linden. DO NOT EDIT.
// systemId: 7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314
// packageScope: @linden
// contractId: foundation.icons
// schemaVersion: 1
// contractRevision: sha256:34aa24e52cc3158dce0e98af2e6127565f4c3d9bb971df254c5fe66d1768b68e
// generatorVersion: 0.1.0

import { createElement, type ComponentType } from "react";
import { ArrowRight as LucideArrowRight, LoaderCircle as LucideLoaderCircle, Plus as LucidePlus, type LucideProps } from "lucide-react";

export type LindenIconProps = Omit<LucideProps, "size" | "width" | "height" | "color">;

function renderIcon(Source: ComponentType<LucideProps>, props: LindenIconProps) {
  const decorative = props["aria-hidden"] === undefined && props["aria-label"] === undefined && props["aria-labelledby"] === undefined;
  return createElement(Source, {
    ...props,
    size: "100%",
    width: "100%",
    height: "100%",
    color: "currentColor",
    focusable: "false",
    "aria-hidden": decorative ? true : props["aria-hidden"],
  });
}

export function ArrowRightIcon(props: LindenIconProps) {
  return renderIcon(LucideArrowRight, props);
}

export function LoaderCircleIcon(props: LindenIconProps) {
  return renderIcon(LucideLoaderCircle, props);
}

export function PlusIcon(props: LindenIconProps) {
  return renderIcon(LucidePlus, props);
}

export const iconComponents = {
  "icon.arrow-right": ArrowRightIcon,
  "icon.loader-circle": LoaderCircleIcon,
  "icon.plus": PlusIcon,
} as const;

export type IconAssetId = keyof typeof iconComponents;

export const iconReferences = {
  "icon.arrow-right": "foundation.icons.icon.arrow-right",
  "icon.loader-circle": "foundation.icons.icon.loader-circle",
  "icon.plus": "foundation.icons.icon.plus"
} as const satisfies Record<IconAssetId, `foundation.icons.${IconAssetId}`>;


export const iconKeyline = {
  "persistent": true,
  "sizeOwner": "consumer-token",
  "fit": "contain",
  "color": "currentColor",
  "swapGeometry": "fixed",
  "decorativeByDefault": true
} as const;

export const iconProvenance = {
  "systemId": "7c1d3e2a-9f64-4b8e-a1d7-6e5c2f908314",
  "packageScope": "@linden",
  "schemaVersion": 1,
  "contractId": "foundation.icons",
  "contractRevision": "sha256:34aa24e52cc3158dce0e98af2e6127565f4c3d9bb971df254c5fe66d1768b68e",
  "generatorVersion": "0.1.0"
} as const;
