import {
  defineTokensContract,
  TOKEN_MODES,
} from "../../contracts/tokens.ts";
import type { TokenDefinition } from "../../contracts/tokens.ts";

const color = (red: number, green: number, blue: number, alpha = 1) => ({
  colorSpace: "srgb" as const,
  components: [red / 255, green / 255, blue / 255] as const,
  ...(alpha === 1 ? {} : { alpha }),
});

const hexColor = (value: string, alpha = 1) => ({
  ...color(Number.parseInt(value.slice(1, 3), 16), Number.parseInt(value.slice(3, 5), 16), Number.parseInt(value.slice(5, 7), 16), alpha),
  hex: value.toUpperCase(),
});

const dimension = (value: number) => ({ value, unit: "px" as const });
const angle = (value: number) => ({ value, unit: "deg" as const });
const duration = (value: number) => ({ value, unit: "ms" as const });

const typographySteps = {
  xs: { mobile: [12, 16, 0.8], desktop: [11, 16, 0.7] },
  sm: { mobile: [14, 20, 0.4], desktop: [12, 16, 0.35] },
  md: { mobile: [16, 24, 0], desktop: [14, 20, 0] },
  lg: { mobile: [18, 28, -0.4], desktop: [16, 24, -0.35] },
  xl: { mobile: [20, 28, -0.4], desktop: [18, 28, -0.35] },
  "2xl": { mobile: [24, 32, -0.4], desktop: [20, 28, -0.35] },
  "3xl": { mobile: [30, 36, -0.8], desktop: [24, 32, -0.7] },
  "4xl": { mobile: [36, 40, -0.8], desktop: [30, 36, -0.7] },
  "5xl": { mobile: [48, 48, -0.8], desktop: [36, 40, -0.7] },
  "6xl": { mobile: [60, 60, -0.8], desktop: [48, 48, -0.7] },
  "7xl": { mobile: [72, 72, -0.8], desktop: [60, 60, -0.7] },
  "8xl": { mobile: [96, 96, -0.8], desktop: [72, 72, -0.7] },
  "9xl": { mobile: [128, 128, -0.8], desktop: [96, 96, -0.7] },
} as const;
type TypographyStep = keyof typeof typographySteps;
type TypographyMetric = "size" | "leading" | "tracking";
type TypographyBaseTokenName = `${TypographyMetric}.${TypographyStep}`;

const typographyBaseTokenEntries = (Object.entries(typographySteps) as [TypographyStep, (typeof typographySteps)[TypographyStep]][])
  .flatMap(([step, modes]) => {
    const metric = (name: TypographyMetric, metricIndex: 0 | 1 | 2, description: string) => [
      `${name}.${step}`,
      {
        $type: "dimension" as const,
        $value: {
          platform: {
            mobile: dimension(modes.mobile[metricIndex]),
            desktop: dimension(modes.desktop[metricIndex]),
          },
        },
        $description: description,
      },
    ] as const;
    return [
      metric("size", 0, "Platform base font size."),
      metric("leading", 1, "Platform base line height."),
      metric("tracking", 2, "Platform base letter spacing."),
    ];
  });
const typographyBaseTokens = Object.fromEntries(typographyBaseTokenEntries) as Record<TypographyBaseTokenName, (typeof typographyBaseTokenEntries)[number][1]>;

const typographyRoles = {
  display: { large: "6xl", medium: "5xl", small: "4xl" },
  headline: { large: "3xl", medium: "3xl", small: "2xl" },
  title: { large: "xl", medium: "md", small: "sm" },
  body: { large: "md", medium: "md", small: "xs" },
  label: { large: "sm", medium: "xs", small: "xs" },
} as const satisfies Record<string, Record<string, TypographyStep>>;

const typographyMetricTokens = Object.fromEntries(
  Object.entries(typographyRoles).flatMap(([role, variants]) =>
    Object.entries(variants).flatMap(([variant, step]) =>
      (["size", "leading", "tracking"] as const).map((metric) => [
        `${metric}.${role}.${variant}`,
        { $type: "dimension" as const, $value: `{${metric}.${step}}`, $description: `Semantic ${metric} for ${role} ${variant}.` },
      ]),
    ),
  ),
);

const textWeightAliases = {
  "display.large.default": "400", "display.large.emphasized": "500", "display.large.expressive": "300",
  "display.medium.default": "400", "display.medium.emphasized": "500", "display.medium.expressive": "300",
  "display.small.default": "400", "display.small.emphasized": "500", "display.small.expressive": "300",
  "headline.large.default": "400", "headline.large.emphasized": "500", "headline.large.expressive": "300",
  "headline.medium.default": "400", "headline.medium.emphasized": "500", "headline.medium.expressive": "300",
  "headline.small.default": "400", "headline.small.emphasized": "500",
  "title.large.default": "500", "title.large.emphasized": "500",
  "title.medium.default": "500", "title.medium.emphasized": "700",
  "title.small.default": "500", "title.small.emphasized": "700",
  "body.large.default": "400", "body.large.emphasized": "500",
  "body.medium.default": "400", "body.medium.emphasized": "500",
  "body.small.default": "400", "body.small.emphasized": "500",
  "label.large.default": "500", "label.large.emphasized": "700",
  "label.medium.default": "500", "label.medium.emphasized": "700",
  "label.small.default": "500", "label.small.emphasized": "700",
} as const;
const textWeightTokens = Object.fromEntries(Object.entries(textWeightAliases).map(([name, weight]) => [
  `weight.${name}`,
  { $type: "fontWeight" as const, $value: `{weight.${weight}}`, $description: `Typography treatment for ${name}.` },
]));

const baseDimensionSteps = {
  0: [0, 0], px: [1, 1], "0-5": [2, 2], 1: [4, 4], "1-5": [6, 6], 2: [8, 8], "2-5": [10, 8], 3: [12, 10], "3-5": [14, 12], 4: [16, 14], 5: [20, 16], 6: [24, 20], 7: [28, 24], 8: [32, 28], 9: [36, 30], 10: [40, 32], 11: [44, 36], 12: [48, 40], 14: [56, 48], 15: [60, 52], 16: [64, 56], 18: [72, 60], 20: [80, 64], 24: [96, 80], 28: [112, 96], 32: [128, 112], 36: [144, 128], 40: [160, 144], 44: [176, 160], 48: [192, 176], 52: [208, 192], 56: [224, 208], 60: [240, 224], 64: [256, 240], 72: [288, 256], 80: [320, 288], 96: [384, 320], 112: [448, 448], 128: [512, 512], 144: [576, 576], 160: [640, 640], 168: [672, 672], 192: [768, 768], 224: [896, 896], 256: [1024, 1024], 288: [1152, 1152], 320: [1280, 1280], 384: [1536, 1536],
} as const satisfies Record<string, readonly [number, number]>;

const baseDimensionTokens = Object.fromEntries(Object.entries(baseDimensionSteps).map(([step, [mobile, desktop]]) => [
  `dimension.${step}`,
  { $type: "dimension" as const, $value: { platform: { mobile: dimension(mobile), desktop: dimension(desktop) } }, $description: "Platform base dimension step." },
]));

const everydayDimensionSteps = ["0", "px", "0-5", "1", "1-5", "2", "2-5", "3", "3-5", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15", "16", "18", "20", "24", "28", "32", "36", "40", "44", "48", "52", "56", "60", "64", "72", "80", "96"] as const;
const usageDimensionTokens = Object.fromEntries(
  (["gap", "padding", "margin", "gutter"] as const).flatMap((family) => everydayDimensionSteps.map((step) => [
    `${family}.${step}`,
    { $type: "dimension" as const, $value: `{dimension.${step}}`, $description: `${family} semantic step.` },
  ])),
);

const motionDurationTokens = Object.fromEntries([0, 50, 100, 150, 200, 250, 300, 400, 500, 700, 1000].map((value) => [
  `motion.duration.${value}`,
  { $type: "duration" as const, $value: duration(value), $description: "Base motion duration." },
]));
const motionDelayTokens = Object.fromEntries([0, 50, 100, 200].map((value) => [
  `motion.delay.${value}`,
  { $type: "duration" as const, $value: duration(value), $description: "Base motion delay." },
]));
const motionEasingTokens = {
  "motion.easing.linear": { $type: "cubicBezier" as const, $value: [0, 0, 1, 1] as const, $description: "Linear easing." },
  "motion.easing.standard": { $type: "cubicBezier" as const, $value: [0.2, 0, 0, 1] as const, $description: "Standard easing." },
  "motion.easing.accelerate": { $type: "cubicBezier" as const, $value: [0.3, 0, 1, 1] as const, $description: "Accelerate easing." },
  "motion.easing.decelerate": { $type: "cubicBezier" as const, $value: [0, 0, 0, 1] as const, $description: "Decelerate easing." },
  "motion.easing.emphasized-accelerate": { $type: "cubicBezier" as const, $value: [0.3, 0, 0.8, 0.15] as const, $description: "Emphasized accelerate easing." },
  "motion.easing.emphasized-decelerate": { $type: "cubicBezier" as const, $value: [0.05, 0.7, 0.1, 1] as const, $description: "Emphasized decelerate easing." },
};
const motionSpringTokens = Object.fromEntries(Object.entries({
  gentle: [1, 180, 22, 0], standard: [1, 300, 30, 0], snappy: [1, 500, 35, 0],
} as const).flatMap(([preset, values]) =>
  (["mass", "stiffness", "damping", "velocity"] as const).map((parameter, index) => [
    `motion.spring.${preset}.${parameter}`,
    { $type: "number" as const, $value: values[index], $description: `${preset} spring ${parameter}.`, $extensions: { "org.linden.spring": { preset, parameter } } },
  ]),
));
const motionTransitionTokens = Object.fromEntries(Object.entries({
  "enter.fast": [150, "decelerate"], "enter.standard": [250, "emphasized-decelerate"], "enter.slow": [400, "emphasized-decelerate"],
  "exit.fast": [100, "accelerate"], "exit.standard": [200, "emphasized-accelerate"], "exit.slow": [300, "emphasized-accelerate"],
  "move.fast": [150, "standard"], "move.standard": [250, "standard"], "move.slow": [400, "standard"],
} as const).map(([name, [durationValue, easing]]) => [
  `motion.${name}`,
  { $type: "transition" as const, $value: { duration: `{motion.duration.${durationValue}}`, delay: "{motion.delay.0}", timingFunction: `{motion.easing.${easing}}` }, $description: `${name} transition.` },
]));

export const tokensContract = defineTokensContract({
  id: "foundation.tokens",
  schemaVersion: 2,
  purpose: "Shared system-foundation tokens for components and documentation.",
  modes: TOKEN_MODES,
  tokens: {
    "color.base.slate-50": { $type: "color", $value: hexColor("#f8fafc"), $description: "Pinned Tailwind base step." },
    "color.base.slate-100": { $type: "color", $value: hexColor("#f1f5f9"), $description: "Pinned Tailwind base step." },
    "color.base.slate-200": { $type: "color", $value: hexColor("#e2e8f0"), $description: "Pinned Tailwind base step." },
    "color.base.slate-300": { $type: "color", $value: hexColor("#cad5e2"), $description: "Pinned Tailwind base step." },
    "color.base.slate-400": { $type: "color", $value: hexColor("#90a1b9"), $description: "Pinned Tailwind base step." },
    "color.base.slate-500": { $type: "color", $value: hexColor("#62748e"), $description: "Pinned Tailwind base step." },
    "color.base.slate-600": { $type: "color", $value: hexColor("#45556c"), $description: "Pinned Tailwind base step." },
    "color.base.slate-700": { $type: "color", $value: hexColor("#314158"), $description: "Pinned Tailwind base step." },
    "color.base.slate-800": { $type: "color", $value: hexColor("#1d293d"), $description: "Pinned Tailwind base step." },
    "color.base.slate-900": { $type: "color", $value: hexColor("#0f172b"), $description: "Pinned Tailwind base step." },
    "color.base.slate-950": { $type: "color", $value: hexColor("#020618"), $description: "Pinned Tailwind base step." },
    "color.base.stone-50": { $type: "color", $value: hexColor("#fafaf9"), $description: "Pinned Tailwind base step." },
    "color.base.stone-100": { $type: "color", $value: hexColor("#f5f5f4"), $description: "Pinned Tailwind base step." },
    "color.base.stone-200": { $type: "color", $value: hexColor("#e7e5e4"), $description: "Pinned Tailwind base step." },
    "color.base.stone-300": { $type: "color", $value: hexColor("#d6d3d1"), $description: "Pinned Tailwind base step." },
    "color.base.stone-400": { $type: "color", $value: hexColor("#a6a09b"), $description: "Pinned Tailwind base step." },
    "color.base.stone-500": { $type: "color", $value: hexColor("#79716b"), $description: "Pinned Tailwind base step." },
    "color.base.stone-600": { $type: "color", $value: hexColor("#57534d"), $description: "Pinned Tailwind base step." },
    "color.base.stone-700": { $type: "color", $value: hexColor("#44403b"), $description: "Pinned Tailwind base step." },
    "color.base.stone-800": { $type: "color", $value: hexColor("#292524"), $description: "Pinned Tailwind base step." },
    "color.base.stone-900": { $type: "color", $value: hexColor("#1c1917"), $description: "Pinned Tailwind base step." },
    "color.base.stone-950": { $type: "color", $value: hexColor("#0c0a09"), $description: "Pinned Tailwind base step." },
    "color.base.red-50": { $type: "color", $value: hexColor("#fef2f2"), $description: "Pinned Tailwind base step." },
    "color.base.red-100": { $type: "color", $value: hexColor("#ffe2e2"), $description: "Pinned Tailwind base step." },
    "color.base.red-200": { $type: "color", $value: hexColor("#ffc9c9"), $description: "Pinned Tailwind base step." },
    "color.base.red-300": { $type: "color", $value: hexColor("#ffa2a2"), $description: "Pinned Tailwind base step." },
    "color.base.red-400": { $type: "color", $value: hexColor("#ff6467"), $description: "Pinned Tailwind base step." },
    "color.base.red-500": { $type: "color", $value: hexColor("#fb2c36"), $description: "Pinned Tailwind base step." },
    "color.base.red-600": { $type: "color", $value: hexColor("#e7000b"), $description: "Pinned Tailwind base step." },
    "color.base.red-700": { $type: "color", $value: hexColor("#c10007"), $description: "Pinned Tailwind base step." },
    "color.base.red-800": { $type: "color", $value: hexColor("#9f0712"), $description: "Pinned Tailwind base step." },
    "color.base.red-900": { $type: "color", $value: hexColor("#82181a"), $description: "Pinned Tailwind base step." },
    "color.base.red-950": { $type: "color", $value: hexColor("#460809"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-50": { $type: "color", $value: hexColor("#ecfdf5"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-100": { $type: "color", $value: hexColor("#d0fae5"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-200": { $type: "color", $value: hexColor("#a4f4cf"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-300": { $type: "color", $value: hexColor("#5ee9b5"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-400": { $type: "color", $value: hexColor("#00d492"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-500": { $type: "color", $value: hexColor("#00bc7d"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-600": { $type: "color", $value: hexColor("#009966"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-700": { $type: "color", $value: hexColor("#007a55"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-800": { $type: "color", $value: hexColor("#006045"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-900": { $type: "color", $value: hexColor("#004f3b"), $description: "Pinned Tailwind base step." },
    "color.base.emerald-950": { $type: "color", $value: hexColor("#002c22"), $description: "Pinned Tailwind base step." },
    "color.base.blue-50": { $type: "color", $value: hexColor("#eff6ff"), $description: "Pinned Tailwind base step." },
    "color.base.blue-100": { $type: "color", $value: hexColor("#dbeafe"), $description: "Pinned Tailwind base step." },
    "color.base.blue-200": { $type: "color", $value: hexColor("#bedbff"), $description: "Pinned Tailwind base step." },
    "color.base.blue-300": { $type: "color", $value: hexColor("#8ec5ff"), $description: "Pinned Tailwind base step." },
    "color.base.blue-400": { $type: "color", $value: hexColor("#50a2ff"), $description: "Pinned Tailwind base step." },
    "color.base.blue-500": { $type: "color", $value: hexColor("#2b7fff"), $description: "Pinned Tailwind base step." },
    "color.base.blue-600": { $type: "color", $value: hexColor("#155dfc"), $description: "Pinned Tailwind base step." },
    "color.base.blue-700": { $type: "color", $value: hexColor("#1447e6"), $description: "Pinned Tailwind base step." },
    "color.base.blue-800": { $type: "color", $value: hexColor("#193cb8"), $description: "Pinned Tailwind base step." },
    "color.base.blue-900": { $type: "color", $value: hexColor("#1c398e"), $description: "Pinned Tailwind base step." },
    "color.base.blue-950": { $type: "color", $value: hexColor("#162556"), $description: "Pinned Tailwind base step." },
    "color.base.white-default": { $type: "color", $value: hexColor("#ffffff"), $description: "Pinned Tailwind base step." },
    "color.base.white-5": { $type: "color", $value: hexColor("#ffffff", 0.05), $description: "Pinned Tailwind base step." },
    "color.base.white-10": { $type: "color", $value: hexColor("#ffffff", 0.1), $description: "Pinned Tailwind base step." },
    "color.base.black-default": { $type: "color", $value: hexColor("#000000"), $description: "Pinned Tailwind base step." },
    "color.base.black-4": { $type: "color", $value: hexColor("#000000", 0.04), $description: "Base black opacity step for elevation." },
    "color.base.black-5": { $type: "color", $value: hexColor("#000000", 0.05), $description: "Pinned Tailwind base step." },
    "color.base.black-6": { $type: "color", $value: hexColor("#000000", 0.06), $description: "Base black opacity step for elevation." },
    "color.base.black-8": { $type: "color", $value: hexColor("#000000", 0.08), $description: "Base black opacity step for elevation." },
    "color.base.black-10": { $type: "color", $value: hexColor("#000000", 0.1), $description: "Pinned Tailwind base step." },
    "color.base.black-12": { $type: "color", $value: hexColor("#000000", 0.12), $description: "Base black opacity step for elevation." },
    "color.base.black-14": { $type: "color", $value: hexColor("#000000", 0.14), $description: "Base black opacity step for elevation." },
    "color.shadow.4": { $type: "color", $value: { colorScheme: { light: "{color.base.black-4}", dark: "{color.base.black-4}" } }, $description: "Elevation shadow color at 4% opacity." },
    "color.shadow.5": { $type: "color", $value: { colorScheme: { light: "{color.base.black-5}", dark: "{color.base.black-5}" } }, $description: "Elevation shadow color at 5% opacity." },
    "color.shadow.6": { $type: "color", $value: { colorScheme: { light: "{color.base.black-6}", dark: "{color.base.black-6}" } }, $description: "Elevation shadow color at 6% opacity." },
    "color.shadow.8": { $type: "color", $value: { colorScheme: { light: "{color.base.black-8}", dark: "{color.base.black-8}" } }, $description: "Elevation shadow color at 8% opacity." },
    "color.shadow.10": { $type: "color", $value: { colorScheme: { light: "{color.base.black-10}", dark: "{color.base.black-10}" } }, $description: "Elevation shadow color at 10% opacity." },
    "color.shadow.12": { $type: "color", $value: { colorScheme: { light: "{color.base.black-12}", dark: "{color.base.black-12}" } }, $description: "Elevation shadow color at 12% opacity." },
    "color.shadow.14": { $type: "color", $value: { colorScheme: { light: "{color.base.black-14}", dark: "{color.base.black-14}" } }, $description: "Elevation shadow color at 14% opacity." },
    "color.fill.default": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.white-default}",
          dark: "{color.base.stone-950}",
        },
      },
      $description: "Default fill.",
    },
    "color.fill.surface": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.white-default}",
          dark: "{color.base.stone-900}",
        },
      },
      $description: "Documentation surface fill.",
    },
    "color.fill.surface-muted": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-100}",
          dark: "{color.base.stone-800}",
        },
      },
      $description: "Muted documentation surface fill.",
    },
    "color.text.surface-primary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-950}",
          dark: "{color.base.stone-50}",
        },
      },
      $description: "Primary documentation surface text.",
    },
    "color.text.surface-secondary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-600}",
          dark: "{color.base.stone-400}",
        },
      },
      $description: "Secondary documentation surface text.",
    },
    "color.border.surface": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-200}",
          dark: "{color.base.stone-800}",
        },
      },
      $description: "Documentation surface border.",
    },
    "color.fill.primary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-900}",
          dark: "{color.base.stone-200}",
        },
      },
      $description: "Primary fill.",
    },
    "color.fill.primary-hover": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-800}",
          dark: "{color.base.stone-300}",
        },
      },
      $description: "Primary hover fill.",
    },
    "color.fill.primary-pressed": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-950}",
          dark: "{color.base.stone-400}",
        },
      },
      $description: "Primary pressed fill.",
    },
    "color.text.on-primary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-50}",
          dark: "{color.base.stone-900}",
        },
      },
      $description: "Text on primary fill.",
    },
    "color.border.primary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.fill.primary}",
          dark: "{color.fill.primary}",
        },
      },
      $description: "Primary border.",
    },
    "color.fill.secondary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.white-default}",
          dark: "{color.base.stone-950}",
        },
      },
      $description: "Secondary fill.",
    },
    "color.fill.secondary-hover": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-100}",
          dark: "{color.base.stone-800}",
        },
      },
      $description: "Secondary hover fill.",
    },
    "color.fill.secondary-pressed": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-200}",
          dark: "{color.base.stone-700}",
        },
      },
      $description: "Secondary pressed fill.",
    },
    "color.text.on-secondary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-900}",
          dark: "{color.base.stone-50}",
        },
      },
      $description: "Text on secondary fill.",
    },
    "color.border.secondary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-200}",
          dark: "{color.base.stone-800}",
        },
      },
      $description: "Secondary border.",
    },
    "color.fill.tertiary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.fill.default}",
          dark: "{color.fill.default}",
        },
      },
      $description: "Tertiary fill uses the default fill.",
    },
    "color.fill.tertiary-hover": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.fill.secondary-hover}",
          dark: "{color.fill.secondary-hover}",
        },
      },
      $description: "Tertiary hover fill follows the secondary hover fill.",
    },
    "color.fill.tertiary-pressed": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.fill.secondary-pressed}",
          dark: "{color.fill.secondary-pressed}",
        },
      },
      $description: "Tertiary pressed fill follows the secondary pressed fill.",
    },
    "color.text.primary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-950}",
          dark: "{color.base.stone-50}",
        },
      },
      $description: "Primary text.",
    },
    "color.border.tertiary": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.fill.tertiary}",
          dark: "{color.fill.tertiary}",
        },
      },
      $description: "Tertiary border.",
    },
    "color.fill.danger": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.red-700}",
          dark: "{color.base.red-600}",
        },
      },
      $description: "Danger action fill.",
    },
    "color.fill.danger-hover": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.red-800}",
          dark: "{color.base.red-700}",
        },
      },
      $description: "Danger hover fill.",
    },
    "color.fill.danger-pressed": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.red-900}",
          dark: "{color.base.red-800}",
        },
      },
      $description: "Danger pressed fill.",
    },
    "color.text.on-danger": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.white-default}",
          dark: "{color.base.white-default}",
        },
      },
      $description: "Text and icon color on danger fill.",
    },
    "color.border.danger": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.fill.danger}",
          dark: "{color.fill.danger}",
        },
      },
      $description: "Danger border follows the danger fill.",
    },
    "color.fill.success-subtle": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.emerald-50}",
          dark: "{color.base.emerald-950}",
        },
      },
      $description: "Subtle success documentation panel fill.",
    },
    "color.border.success": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.emerald-200}",
          dark: "{color.base.emerald-800}",
        },
      },
      $description: "Success documentation panel border.",
    },
    "color.text.success": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.emerald-800}",
          dark: "{color.base.emerald-200}",
        },
      },
      $description: "Success documentation panel text.",
    },
    "color.fill.danger-subtle": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.red-50}",
          dark: "{color.base.red-950}",
        },
      },
      $description: "Subtle danger documentation panel fill.",
    },
    "color.border.danger-subtle": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.red-200}",
          dark: "{color.base.red-800}",
        },
      },
      $description: "Subtle danger documentation panel border.",
    },
    "color.text.danger": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.red-800}",
          dark: "{color.base.red-200}",
        },
      },
      $description: "Danger documentation panel text.",
    },
    "opacity.base.0": { $type: "number", $value: 0, $description: "Pinned Tailwind base step." },
    "opacity.base.5": { $type: "number", $value: 0.05, $description: "Pinned Tailwind base step." },
    "opacity.base.10": { $type: "number", $value: 0.1, $description: "Pinned Tailwind base step." },
    "opacity.base.15": { $type: "number", $value: 0.15, $description: "Pinned Tailwind base step." },
    "opacity.base.20": { $type: "number", $value: 0.2, $description: "Pinned Tailwind base step." },
    "opacity.base.25": { $type: "number", $value: 0.25, $description: "Pinned Tailwind base step." },
    "opacity.base.30": { $type: "number", $value: 0.3, $description: "Pinned Tailwind base step." },
    "opacity.base.35": { $type: "number", $value: 0.35, $description: "Pinned Tailwind base step." },
    "opacity.base.40": { $type: "number", $value: 0.4, $description: "Pinned Tailwind base step." },
    "opacity.base.45": { $type: "number", $value: 0.45, $description: "Pinned Tailwind base step." },
    "opacity.base.50": { $type: "number", $value: 0.5, $description: "Pinned Tailwind base step." },
    "opacity.base.55": { $type: "number", $value: 0.55, $description: "Pinned Tailwind base step." },
    "opacity.base.60": { $type: "number", $value: 0.6, $description: "Pinned Tailwind base step." },
    "opacity.base.65": { $type: "number", $value: 0.65, $description: "Pinned Tailwind base step." },
    "opacity.base.70": { $type: "number", $value: 0.7, $description: "Pinned Tailwind base step." },
    "opacity.base.75": { $type: "number", $value: 0.75, $description: "Pinned Tailwind base step." },
    "opacity.base.80": { $type: "number", $value: 0.8, $description: "Pinned Tailwind base step." },
    "opacity.base.85": { $type: "number", $value: 0.85, $description: "Pinned Tailwind base step." },
    "opacity.base.90": { $type: "number", $value: 0.9, $description: "Pinned Tailwind base step." },
    "opacity.base.95": { $type: "number", $value: 0.95, $description: "Pinned Tailwind base step." },
    "opacity.base.100": { $type: "number", $value: 1, $description: "Pinned Tailwind base step." },
    "color.state.focused": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.stone-400}",
          dark: "{color.base.stone-500}",
        },
      },
      $description: "Keyboard focus outline color.",
    },
    "color.overlay.hover": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.black-5}",
          dark: "{color.base.white-5}",
        },
      },
      $description: "Hover overlay.",
    },
    "color.overlay.pressed": {
      $type: "color",
      $value: {
        colorScheme: {
          light: "{color.base.black-10}",
          dark: "{color.base.white-10}",
        },
      },
      $description: "Pressed overlay.",
    },
    ...baseDimensionTokens,
    "family.sans": { $type: "fontFamily", $value: "Geist", $description: "Canonical interface font family." },
    "family.mono": { $type: "fontFamily", $value: "Geist Mono", $description: "Canonical monospaced font family." },
    "family.nunito-sans": { $type: "fontFamily", $value: "Nunito Sans", $description: "Supported alternative sans-serif family." },
    "family.jetbrains-mono": { $type: "fontFamily", $value: "JetBrains Mono", $description: "Supported alternative monospaced family." },
    "style.normal": { $type: "fontStyle", $value: "normal", $description: "Normal font style." },
    "style.italic": { $type: "fontStyle", $value: "italic", $description: "Italic font style." },
    "weight.100": { $type: "fontWeight", $value: 100, $description: "Thin font weight." },
    "weight.200": { $type: "fontWeight", $value: 200, $description: "Extra-light font weight." },
    "weight.300": { $type: "fontWeight", $value: 300, $description: "Light font weight." },
    "weight.400": { $type: "fontWeight", $value: 400, $description: "Regular font weight." },
    "weight.500": { $type: "fontWeight", $value: 500, $description: "Medium font weight." },
    "weight.600": { $type: "fontWeight", $value: 600, $description: "Semibold font weight." },
    "weight.700": { $type: "fontWeight", $value: 700, $description: "Bold font weight." },
    "weight.800": { $type: "fontWeight", $value: 800, $description: "Extra-bold font weight." },
    "weight.900": { $type: "fontWeight", $value: 900, $description: "Black font weight." },
    ...typographyBaseTokens,
    "family.default": { $type: "fontFamily", $value: "{family.sans}", $description: "Default text family." },
    "family.monospace": { $type: "fontFamily", $value: "{family.mono}", $description: "Default monospaced text family." },
    "style.default": { $type: "fontStyle", $value: "{style.normal}", $description: "Default text style." },
    ...typographyMetricTokens,
    ...textWeightTokens,
    "size.control.md": { $type: "dimension", $value: "{size.md}", $description: "Control label size." },
    "leading.control.md": { $type: "dimension", $value: "{leading.md}", $description: "Control label leading." },
    "tracking.control.md": { $type: "dimension", $value: "{tracking.md}", $description: "Control label tracking." },
    "weight.control.default": { $type: "fontWeight", $value: "{weight.500}", $description: "Control label weight." },
    "family.control.default": { $type: "fontFamily", $value: "{family.sans}", $description: "Control label family." },
    "style.control.default": { $type: "fontStyle", $value: "{style.normal}", $description: "Control label style." },
    ...usageDimensionTokens,
    "radius.none": { $type: "dimension", $value: "{dimension.0}", $description: "No corner radius." },
    "radius.xs": { $type: "dimension", $value: "{dimension.0-5}", $description: "Extra-small corner radius." },
    "radius.sm": { $type: "dimension", $value: "{dimension.1}", $description: "Small corner radius." },
    "radius.md": { $type: "dimension", $value: "{dimension.1-5}", $description: "Medium corner radius." },
    "radius.lg": { $type: "dimension", $value: "{dimension.2-5}", $description: "Large corner radius." },
    "radius.xl": { $type: "dimension", $value: "{dimension.3-5}", $description: "Extra-large corner radius." },
    "radius.2xl": { $type: "dimension", $value: "{dimension.5}", $description: "2XL corner radius." },
    "radius.3xl": { $type: "dimension", $value: "{dimension.7}", $description: "3XL corner radius." },
    "radius.4xl": { $type: "dimension", $value: "{dimension.8}", $description: "4XL corner radius." },
    "radius.full": { $type: "dimension", $value: dimension(9999), $description: "Direct full-radius exception." },
    "border-width.0": { $type: "dimension", $value: "{dimension.0}", $description: "No UI border." },
    "border-width.1": { $type: "dimension", $value: "{dimension.px}", $description: "Default UI border." },
    "border-width.2": { $type: "dimension", $value: "{dimension.0-5}", $description: "Two-pixel UI border." },
    "border-width.4": { $type: "dimension", $value: "{dimension.1}", $description: "Four-pixel UI border." },
    "border-width.8": { $type: "dimension", $value: "{dimension.2}", $description: "Eight-pixel UI border." },
    "focus-ring.offset-sm": { $type: "dimension", $value: "{dimension.0-5}", $description: "Two-pixel focus-ring offset." },
    "focus-ring.offset-md": { $type: "dimension", $value: "{dimension.1}", $description: "Default four-pixel focus-ring offset." },
    "focus-ring.offset-lg": { $type: "dimension", $value: "{dimension.1-5}", $description: "Six-pixel focus-ring offset." },
    "blur.none": { $type: "dimension", $value: "{dimension.0}", $description: "No blur." },
    "blur.xs": { $type: "dimension", $value: "{dimension.1}", $description: "Extra-small blur." },
    "blur.sm": { $type: "dimension", $value: "{dimension.2}", $description: "Small blur." },
    "blur.md": { $type: "dimension", $value: "{dimension.3}", $description: "Medium blur." },
    "blur.lg": { $type: "dimension", $value: "{dimension.4}", $description: "Large blur." },
    "blur.xl": { $type: "dimension", $value: "{dimension.6}", $description: "Extra-large blur." },
    "blur.2xl": { $type: "dimension", $value: "{dimension.10}", $description: "2XL blur." },
    "blur.3xl": { $type: "dimension", $value: "{dimension.16}", $description: "3XL blur." },
    "breakpoint.sm": { $type: "dimension", $value: "{dimension.160}", $description: "Small breakpoint." },
    "breakpoint.md": { $type: "dimension", $value: "{dimension.192}", $description: "Medium breakpoint." },
    "breakpoint.lg": { $type: "dimension", $value: "{dimension.256}", $description: "Large breakpoint." },
    "breakpoint.xl": { $type: "dimension", $value: "{dimension.320}", $description: "Extra-large breakpoint." },
    "breakpoint.2xl": { $type: "dimension", $value: "{dimension.384}", $description: "2XL breakpoint." },
    "container.2xs": { $type: "dimension", $value: "{dimension.64}", $description: "2XS container." },
    "container.xs": { $type: "dimension", $value: "{dimension.72}", $description: "XS container." },
    "container.sm": { $type: "dimension", $value: "{dimension.80}", $description: "Small container." },
    "container.md": { $type: "dimension", $value: "{dimension.96}", $description: "Medium container." },
    "container.lg": { $type: "dimension", $value: "{dimension.112}", $description: "Large container." },
    "container.xl": { $type: "dimension", $value: "{dimension.128}", $description: "Extra-large container." },
    "container.2xl": { $type: "dimension", $value: "{dimension.144}", $description: "2XL container." },
    "container.3xl": { $type: "dimension", $value: "{dimension.168}", $description: "3XL container." },
    "container.4xl": { $type: "dimension", $value: "{dimension.192}", $description: "4XL container." },
    "container.5xl": { $type: "dimension", $value: "{dimension.224}", $description: "5XL container." },
    "container.6xl": { $type: "dimension", $value: "{dimension.256}", $description: "6XL container." },
    "container.7xl": { $type: "dimension", $value: "{dimension.288}", $description: "7XL container." },
    "container.8xl": { $type: "dimension", $value: "{dimension.320}", $description: "8XL container." },
    "color.base.gray-50": { $type: "color", $value: hexColor("#F9FAFB"), $description: "Tailwind-compatible base color." },
    "color.base.gray-100": { $type: "color", $value: hexColor("#F3F4F6"), $description: "Tailwind-compatible base color." },
    "color.base.gray-200": { $type: "color", $value: hexColor("#E5E7EB"), $description: "Tailwind-compatible base color." },
    "color.base.gray-300": { $type: "color", $value: hexColor("#D1D5DC"), $description: "Tailwind-compatible base color." },
    "color.base.gray-400": { $type: "color", $value: hexColor("#99A1AF"), $description: "Tailwind-compatible base color." },
    "color.base.gray-500": { $type: "color", $value: hexColor("#6A7282"), $description: "Tailwind-compatible base color." },
    "color.base.gray-600": { $type: "color", $value: hexColor("#4A5565"), $description: "Tailwind-compatible base color." },
    "color.base.gray-700": { $type: "color", $value: hexColor("#364153"), $description: "Tailwind-compatible base color." },
    "color.base.gray-800": { $type: "color", $value: hexColor("#1E2939"), $description: "Tailwind-compatible base color." },
    "color.base.gray-900": { $type: "color", $value: hexColor("#101828"), $description: "Tailwind-compatible base color." },
    "color.base.gray-950": { $type: "color", $value: hexColor("#030712"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-50": { $type: "color", $value: hexColor("#FAFAFA"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-100": { $type: "color", $value: hexColor("#F4F4F5"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-200": { $type: "color", $value: hexColor("#E4E4E7"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-300": { $type: "color", $value: hexColor("#D4D4D8"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-400": { $type: "color", $value: hexColor("#9F9FA9"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-500": { $type: "color", $value: hexColor("#71717B"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-600": { $type: "color", $value: hexColor("#52525C"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-700": { $type: "color", $value: hexColor("#3F3F46"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-800": { $type: "color", $value: hexColor("#27272A"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-900": { $type: "color", $value: hexColor("#18181B"), $description: "Tailwind-compatible base color." },
    "color.base.zinc-950": { $type: "color", $value: hexColor("#09090B"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-50": { $type: "color", $value: hexColor("#FAFAFA"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-100": { $type: "color", $value: hexColor("#F5F5F5"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-200": { $type: "color", $value: hexColor("#E5E5E5"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-300": { $type: "color", $value: hexColor("#D4D4D4"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-400": { $type: "color", $value: hexColor("#A1A1A1"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-500": { $type: "color", $value: hexColor("#737373"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-600": { $type: "color", $value: hexColor("#525252"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-700": { $type: "color", $value: hexColor("#404040"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-800": { $type: "color", $value: hexColor("#262626"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-900": { $type: "color", $value: hexColor("#171717"), $description: "Tailwind-compatible base color." },
    "color.base.neutral-950": { $type: "color", $value: hexColor("#0A0A0A"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-50": { $type: "color", $value: hexColor("#FAFAFA"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-100": { $type: "color", $value: hexColor("#F3F1F3"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-200": { $type: "color", $value: hexColor("#E7E4E7"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-300": { $type: "color", $value: hexColor("#D7D0D7"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-400": { $type: "color", $value: hexColor("#A89EA9"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-500": { $type: "color", $value: hexColor("#79697B"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-600": { $type: "color", $value: hexColor("#594C5B"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-700": { $type: "color", $value: hexColor("#463947"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-800": { $type: "color", $value: hexColor("#2A212C"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-900": { $type: "color", $value: hexColor("#1D161E"), $description: "Tailwind-compatible base color." },
    "color.base.mauve-950": { $type: "color", $value: hexColor("#0C090C"), $description: "Tailwind-compatible base color." },
    "color.base.olive-50": { $type: "color", $value: hexColor("#FBFBF9"), $description: "Tailwind-compatible base color." },
    "color.base.olive-100": { $type: "color", $value: hexColor("#F4F4F0"), $description: "Tailwind-compatible base color." },
    "color.base.olive-200": { $type: "color", $value: hexColor("#E8E8E3"), $description: "Tailwind-compatible base color." },
    "color.base.olive-300": { $type: "color", $value: hexColor("#D8D8D0"), $description: "Tailwind-compatible base color." },
    "color.base.olive-400": { $type: "color", $value: hexColor("#ABAB9C"), $description: "Tailwind-compatible base color." },
    "color.base.olive-500": { $type: "color", $value: hexColor("#7C7C67"), $description: "Tailwind-compatible base color." },
    "color.base.olive-600": { $type: "color", $value: hexColor("#5B5B4B"), $description: "Tailwind-compatible base color." },
    "color.base.olive-700": { $type: "color", $value: hexColor("#474739"), $description: "Tailwind-compatible base color." },
    "color.base.olive-800": { $type: "color", $value: hexColor("#2B2B22"), $description: "Tailwind-compatible base color." },
    "color.base.olive-900": { $type: "color", $value: hexColor("#1D1D16"), $description: "Tailwind-compatible base color." },
    "color.base.olive-950": { $type: "color", $value: hexColor("#0C0C09"), $description: "Tailwind-compatible base color." },
    "color.base.mist-50": { $type: "color", $value: hexColor("#F9FBFB"), $description: "Tailwind-compatible base color." },
    "color.base.mist-100": { $type: "color", $value: hexColor("#F1F3F3"), $description: "Tailwind-compatible base color." },
    "color.base.mist-200": { $type: "color", $value: hexColor("#E3E7E8"), $description: "Tailwind-compatible base color." },
    "color.base.mist-300": { $type: "color", $value: hexColor("#D0D6D8"), $description: "Tailwind-compatible base color." },
    "color.base.mist-400": { $type: "color", $value: hexColor("#9CA8AB"), $description: "Tailwind-compatible base color." },
    "color.base.mist-500": { $type: "color", $value: hexColor("#67787C"), $description: "Tailwind-compatible base color." },
    "color.base.mist-600": { $type: "color", $value: hexColor("#4B585B"), $description: "Tailwind-compatible base color." },
    "color.base.mist-700": { $type: "color", $value: hexColor("#394447"), $description: "Tailwind-compatible base color." },
    "color.base.mist-800": { $type: "color", $value: hexColor("#22292B"), $description: "Tailwind-compatible base color." },
    "color.base.mist-900": { $type: "color", $value: hexColor("#161B1D"), $description: "Tailwind-compatible base color." },
    "color.base.mist-950": { $type: "color", $value: hexColor("#090B0C"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-50": { $type: "color", $value: hexColor("#FBFAF9"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-100": { $type: "color", $value: hexColor("#F3F1F1"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-200": { $type: "color", $value: hexColor("#E8E4E3"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-300": { $type: "color", $value: hexColor("#D8D2D0"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-400": { $type: "color", $value: hexColor("#ABA09C"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-500": { $type: "color", $value: hexColor("#7C6D67"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-600": { $type: "color", $value: hexColor("#5B4F4B"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-700": { $type: "color", $value: hexColor("#473C39"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-800": { $type: "color", $value: hexColor("#2B2422"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-900": { $type: "color", $value: hexColor("#1D1816"), $description: "Tailwind-compatible base color." },
    "color.base.taupe-950": { $type: "color", $value: hexColor("#0C0A09"), $description: "Tailwind-compatible base color." },
    "color.base.orange-50": { $type: "color", $value: hexColor("#FFF7ED"), $description: "Tailwind-compatible base color." },
    "color.base.orange-100": { $type: "color", $value: hexColor("#FFEDD4"), $description: "Tailwind-compatible base color." },
    "color.base.orange-200": { $type: "color", $value: hexColor("#FFD6A7"), $description: "Tailwind-compatible base color." },
    "color.base.orange-300": { $type: "color", $value: hexColor("#FFB86A"), $description: "Tailwind-compatible base color." },
    "color.base.orange-400": { $type: "color", $value: hexColor("#FF8904"), $description: "Tailwind-compatible base color." },
    "color.base.orange-500": { $type: "color", $value: hexColor("#FF6900"), $description: "Tailwind-compatible base color." },
    "color.base.orange-600": { $type: "color", $value: hexColor("#F54900"), $description: "Tailwind-compatible base color." },
    "color.base.orange-700": { $type: "color", $value: hexColor("#CA3500"), $description: "Tailwind-compatible base color." },
    "color.base.orange-800": { $type: "color", $value: hexColor("#9F2D00"), $description: "Tailwind-compatible base color." },
    "color.base.orange-900": { $type: "color", $value: hexColor("#7E2A0C"), $description: "Tailwind-compatible base color." },
    "color.base.orange-950": { $type: "color", $value: hexColor("#441306"), $description: "Tailwind-compatible base color." },
    "color.base.amber-50": { $type: "color", $value: hexColor("#FFFBEB"), $description: "Tailwind-compatible base color." },
    "color.base.amber-100": { $type: "color", $value: hexColor("#FEF3C6"), $description: "Tailwind-compatible base color." },
    "color.base.amber-200": { $type: "color", $value: hexColor("#FEE685"), $description: "Tailwind-compatible base color." },
    "color.base.amber-300": { $type: "color", $value: hexColor("#FFD230"), $description: "Tailwind-compatible base color." },
    "color.base.amber-400": { $type: "color", $value: hexColor("#FFB900"), $description: "Tailwind-compatible base color." },
    "color.base.amber-500": { $type: "color", $value: hexColor("#FE9A00"), $description: "Tailwind-compatible base color." },
    "color.base.amber-600": { $type: "color", $value: hexColor("#E17100"), $description: "Tailwind-compatible base color." },
    "color.base.amber-700": { $type: "color", $value: hexColor("#BB4D00"), $description: "Tailwind-compatible base color." },
    "color.base.amber-800": { $type: "color", $value: hexColor("#973C00"), $description: "Tailwind-compatible base color." },
    "color.base.amber-900": { $type: "color", $value: hexColor("#7B3306"), $description: "Tailwind-compatible base color." },
    "color.base.amber-950": { $type: "color", $value: hexColor("#461901"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-50": { $type: "color", $value: hexColor("#FEFCE8"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-100": { $type: "color", $value: hexColor("#FEF9C2"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-200": { $type: "color", $value: hexColor("#FFF085"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-300": { $type: "color", $value: hexColor("#FFDF20"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-400": { $type: "color", $value: hexColor("#FDC700"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-500": { $type: "color", $value: hexColor("#F0B100"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-600": { $type: "color", $value: hexColor("#D08700"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-700": { $type: "color", $value: hexColor("#A65F00"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-800": { $type: "color", $value: hexColor("#894B00"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-900": { $type: "color", $value: hexColor("#733E0A"), $description: "Tailwind-compatible base color." },
    "color.base.yellow-950": { $type: "color", $value: hexColor("#432004"), $description: "Tailwind-compatible base color." },
    "color.base.lime-50": { $type: "color", $value: hexColor("#F7FEE7"), $description: "Tailwind-compatible base color." },
    "color.base.lime-100": { $type: "color", $value: hexColor("#ECFCCA"), $description: "Tailwind-compatible base color." },
    "color.base.lime-200": { $type: "color", $value: hexColor("#D8F999"), $description: "Tailwind-compatible base color." },
    "color.base.lime-300": { $type: "color", $value: hexColor("#BBF451"), $description: "Tailwind-compatible base color." },
    "color.base.lime-400": { $type: "color", $value: hexColor("#9AE600"), $description: "Tailwind-compatible base color." },
    "color.base.lime-500": { $type: "color", $value: hexColor("#7CCF00"), $description: "Tailwind-compatible base color." },
    "color.base.lime-600": { $type: "color", $value: hexColor("#5EA500"), $description: "Tailwind-compatible base color." },
    "color.base.lime-700": { $type: "color", $value: hexColor("#497D00"), $description: "Tailwind-compatible base color." },
    "color.base.lime-800": { $type: "color", $value: hexColor("#3C6300"), $description: "Tailwind-compatible base color." },
    "color.base.lime-900": { $type: "color", $value: hexColor("#35530E"), $description: "Tailwind-compatible base color." },
    "color.base.lime-950": { $type: "color", $value: hexColor("#192E03"), $description: "Tailwind-compatible base color." },
    "color.base.green-50": { $type: "color", $value: hexColor("#F0FDF4"), $description: "Tailwind-compatible base color." },
    "color.base.green-100": { $type: "color", $value: hexColor("#DCFCE7"), $description: "Tailwind-compatible base color." },
    "color.base.green-200": { $type: "color", $value: hexColor("#B9F8CF"), $description: "Tailwind-compatible base color." },
    "color.base.green-300": { $type: "color", $value: hexColor("#7BF1A8"), $description: "Tailwind-compatible base color." },
    "color.base.green-400": { $type: "color", $value: hexColor("#05DF72"), $description: "Tailwind-compatible base color." },
    "color.base.green-500": { $type: "color", $value: hexColor("#00C950"), $description: "Tailwind-compatible base color." },
    "color.base.green-600": { $type: "color", $value: hexColor("#00A63E"), $description: "Tailwind-compatible base color." },
    "color.base.green-700": { $type: "color", $value: hexColor("#008236"), $description: "Tailwind-compatible base color." },
    "color.base.green-800": { $type: "color", $value: hexColor("#016630"), $description: "Tailwind-compatible base color." },
    "color.base.green-900": { $type: "color", $value: hexColor("#0D542B"), $description: "Tailwind-compatible base color." },
    "color.base.green-950": { $type: "color", $value: hexColor("#032E15"), $description: "Tailwind-compatible base color." },
    "color.base.teal-50": { $type: "color", $value: hexColor("#F0FDFA"), $description: "Tailwind-compatible base color." },
    "color.base.teal-100": { $type: "color", $value: hexColor("#CBFBF1"), $description: "Tailwind-compatible base color." },
    "color.base.teal-200": { $type: "color", $value: hexColor("#96F7E4"), $description: "Tailwind-compatible base color." },
    "color.base.teal-300": { $type: "color", $value: hexColor("#46ECD5"), $description: "Tailwind-compatible base color." },
    "color.base.teal-400": { $type: "color", $value: hexColor("#00D5BE"), $description: "Tailwind-compatible base color." },
    "color.base.teal-500": { $type: "color", $value: hexColor("#00BBA7"), $description: "Tailwind-compatible base color." },
    "color.base.teal-600": { $type: "color", $value: hexColor("#009689"), $description: "Tailwind-compatible base color." },
    "color.base.teal-700": { $type: "color", $value: hexColor("#00786F"), $description: "Tailwind-compatible base color." },
    "color.base.teal-800": { $type: "color", $value: hexColor("#005F5A"), $description: "Tailwind-compatible base color." },
    "color.base.teal-900": { $type: "color", $value: hexColor("#0B4F4A"), $description: "Tailwind-compatible base color." },
    "color.base.teal-950": { $type: "color", $value: hexColor("#022F2E"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-50": { $type: "color", $value: hexColor("#ECFEFF"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-100": { $type: "color", $value: hexColor("#CEFAFE"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-200": { $type: "color", $value: hexColor("#A2F4FD"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-300": { $type: "color", $value: hexColor("#53EAFD"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-400": { $type: "color", $value: hexColor("#00D3F2"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-500": { $type: "color", $value: hexColor("#00B8DB"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-600": { $type: "color", $value: hexColor("#0092B8"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-700": { $type: "color", $value: hexColor("#007595"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-800": { $type: "color", $value: hexColor("#005F78"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-900": { $type: "color", $value: hexColor("#104E64"), $description: "Tailwind-compatible base color." },
    "color.base.cyan-950": { $type: "color", $value: hexColor("#053345"), $description: "Tailwind-compatible base color." },
    "color.base.sky-50": { $type: "color", $value: hexColor("#F0F9FF"), $description: "Tailwind-compatible base color." },
    "color.base.sky-100": { $type: "color", $value: hexColor("#DFF2FE"), $description: "Tailwind-compatible base color." },
    "color.base.sky-200": { $type: "color", $value: hexColor("#B8E6FE"), $description: "Tailwind-compatible base color." },
    "color.base.sky-300": { $type: "color", $value: hexColor("#74D4FF"), $description: "Tailwind-compatible base color." },
    "color.base.sky-400": { $type: "color", $value: hexColor("#00BCFF"), $description: "Tailwind-compatible base color." },
    "color.base.sky-500": { $type: "color", $value: hexColor("#00A6F4"), $description: "Tailwind-compatible base color." },
    "color.base.sky-600": { $type: "color", $value: hexColor("#0084D1"), $description: "Tailwind-compatible base color." },
    "color.base.sky-700": { $type: "color", $value: hexColor("#0069A8"), $description: "Tailwind-compatible base color." },
    "color.base.sky-800": { $type: "color", $value: hexColor("#00598A"), $description: "Tailwind-compatible base color." },
    "color.base.sky-900": { $type: "color", $value: hexColor("#024A70"), $description: "Tailwind-compatible base color." },
    "color.base.sky-950": { $type: "color", $value: hexColor("#052F4A"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-50": { $type: "color", $value: hexColor("#EEF2FF"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-100": { $type: "color", $value: hexColor("#E0E7FF"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-200": { $type: "color", $value: hexColor("#C6D2FF"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-300": { $type: "color", $value: hexColor("#A3B3FF"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-400": { $type: "color", $value: hexColor("#7C86FF"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-500": { $type: "color", $value: hexColor("#615FFF"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-600": { $type: "color", $value: hexColor("#4F39F6"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-700": { $type: "color", $value: hexColor("#432DD7"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-800": { $type: "color", $value: hexColor("#372AAC"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-900": { $type: "color", $value: hexColor("#312C85"), $description: "Tailwind-compatible base color." },
    "color.base.indigo-950": { $type: "color", $value: hexColor("#1E1A4D"), $description: "Tailwind-compatible base color." },
    "color.base.violet-50": { $type: "color", $value: hexColor("#F5F3FF"), $description: "Tailwind-compatible base color." },
    "color.base.violet-100": { $type: "color", $value: hexColor("#EDE9FE"), $description: "Tailwind-compatible base color." },
    "color.base.violet-200": { $type: "color", $value: hexColor("#DDD6FF"), $description: "Tailwind-compatible base color." },
    "color.base.violet-300": { $type: "color", $value: hexColor("#C4B4FF"), $description: "Tailwind-compatible base color." },
    "color.base.violet-400": { $type: "color", $value: hexColor("#A684FF"), $description: "Tailwind-compatible base color." },
    "color.base.violet-500": { $type: "color", $value: hexColor("#8E51FF"), $description: "Tailwind-compatible base color." },
    "color.base.violet-600": { $type: "color", $value: hexColor("#7F22FE"), $description: "Tailwind-compatible base color." },
    "color.base.violet-700": { $type: "color", $value: hexColor("#7008E7"), $description: "Tailwind-compatible base color." },
    "color.base.violet-800": { $type: "color", $value: hexColor("#5D0EC0"), $description: "Tailwind-compatible base color." },
    "color.base.violet-900": { $type: "color", $value: hexColor("#4D179A"), $description: "Tailwind-compatible base color." },
    "color.base.violet-950": { $type: "color", $value: hexColor("#2F0D68"), $description: "Tailwind-compatible base color." },
    "color.base.purple-50": { $type: "color", $value: hexColor("#FAF5FF"), $description: "Tailwind-compatible base color." },
    "color.base.purple-100": { $type: "color", $value: hexColor("#F3E8FF"), $description: "Tailwind-compatible base color." },
    "color.base.purple-200": { $type: "color", $value: hexColor("#E9D4FF"), $description: "Tailwind-compatible base color." },
    "color.base.purple-300": { $type: "color", $value: hexColor("#DAB2FF"), $description: "Tailwind-compatible base color." },
    "color.base.purple-400": { $type: "color", $value: hexColor("#C27AFF"), $description: "Tailwind-compatible base color." },
    "color.base.purple-500": { $type: "color", $value: hexColor("#AD46FF"), $description: "Tailwind-compatible base color." },
    "color.base.purple-600": { $type: "color", $value: hexColor("#9810FA"), $description: "Tailwind-compatible base color." },
    "color.base.purple-700": { $type: "color", $value: hexColor("#8200DB"), $description: "Tailwind-compatible base color." },
    "color.base.purple-800": { $type: "color", $value: hexColor("#6E11B0"), $description: "Tailwind-compatible base color." },
    "color.base.purple-900": { $type: "color", $value: hexColor("#59168B"), $description: "Tailwind-compatible base color." },
    "color.base.purple-950": { $type: "color", $value: hexColor("#3C0366"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-50": { $type: "color", $value: hexColor("#FDF4FF"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-100": { $type: "color", $value: hexColor("#FAE8FF"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-200": { $type: "color", $value: hexColor("#F6CFFF"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-300": { $type: "color", $value: hexColor("#F4A8FF"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-400": { $type: "color", $value: hexColor("#ED6AFF"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-500": { $type: "color", $value: hexColor("#E12AFB"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-600": { $type: "color", $value: hexColor("#C800DE"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-700": { $type: "color", $value: hexColor("#A800B7"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-800": { $type: "color", $value: hexColor("#8A0194"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-900": { $type: "color", $value: hexColor("#721378"), $description: "Tailwind-compatible base color." },
    "color.base.fuchsia-950": { $type: "color", $value: hexColor("#4B004F"), $description: "Tailwind-compatible base color." },
    "color.base.pink-50": { $type: "color", $value: hexColor("#FDF2F8"), $description: "Tailwind-compatible base color." },
    "color.base.pink-100": { $type: "color", $value: hexColor("#FCE7F3"), $description: "Tailwind-compatible base color." },
    "color.base.pink-200": { $type: "color", $value: hexColor("#FCCEE8"), $description: "Tailwind-compatible base color." },
    "color.base.pink-300": { $type: "color", $value: hexColor("#FDA5D5"), $description: "Tailwind-compatible base color." },
    "color.base.pink-400": { $type: "color", $value: hexColor("#FB64B6"), $description: "Tailwind-compatible base color." },
    "color.base.pink-500": { $type: "color", $value: hexColor("#F6339A"), $description: "Tailwind-compatible base color." },
    "color.base.pink-600": { $type: "color", $value: hexColor("#E60076"), $description: "Tailwind-compatible base color." },
    "color.base.pink-700": { $type: "color", $value: hexColor("#C6005C"), $description: "Tailwind-compatible base color." },
    "color.base.pink-800": { $type: "color", $value: hexColor("#A3004C"), $description: "Tailwind-compatible base color." },
    "color.base.pink-900": { $type: "color", $value: hexColor("#861043"), $description: "Tailwind-compatible base color." },
    "color.base.pink-950": { $type: "color", $value: hexColor("#510424"), $description: "Tailwind-compatible base color." },
    "color.base.rose-50": { $type: "color", $value: hexColor("#FFF1F2"), $description: "Tailwind-compatible base color." },
    "color.base.rose-100": { $type: "color", $value: hexColor("#FFE4E6"), $description: "Tailwind-compatible base color." },
    "color.base.rose-200": { $type: "color", $value: hexColor("#FFCCD3"), $description: "Tailwind-compatible base color." },
    "color.base.rose-300": { $type: "color", $value: hexColor("#FFA1AD"), $description: "Tailwind-compatible base color." },
    "color.base.rose-400": { $type: "color", $value: hexColor("#FF637E"), $description: "Tailwind-compatible base color." },
    "color.base.rose-500": { $type: "color", $value: hexColor("#FF2056"), $description: "Tailwind-compatible base color." },
    "color.base.rose-600": { $type: "color", $value: hexColor("#EC003F"), $description: "Tailwind-compatible base color." },
    "color.base.rose-700": { $type: "color", $value: hexColor("#C70036"), $description: "Tailwind-compatible base color." },
    "color.base.rose-800": { $type: "color", $value: hexColor("#A50036"), $description: "Tailwind-compatible base color." },
    "color.base.rose-900": { $type: "color", $value: hexColor("#8B0836"), $description: "Tailwind-compatible base color." },
    "color.base.rose-950": { $type: "color", $value: hexColor("#4D0218"), $description: "Tailwind-compatible base color." },
    "color.base.transparent": { $type: "color", $value: hexColor("#000000", 0), $description: "Tailwind-compatible base color." },
    "angle.skew.0": { $type: "angle", $value: angle(0), $description: "Base skew angle." },
    "angle.skew.1": { $type: "angle", $value: angle(1), $description: "Base skew angle." },
    "angle.skew.2": { $type: "angle", $value: angle(2), $description: "Base skew angle." },
    "angle.skew.3": { $type: "angle", $value: angle(3), $description: "Base skew angle." },
    "angle.skew.6": { $type: "angle", $value: angle(6), $description: "Base skew angle." },
    "angle.skew.12": { $type: "angle", $value: angle(12), $description: "Base skew angle." },
    ...motionDurationTokens,
    ...motionDelayTokens,
    ...motionEasingTokens,
    ...motionSpringTokens,
    ...motionTransitionTokens,
    "motion.duration.loading-spinner": { $type: "duration", $value: "{motion.duration.1000}", $description: "One loading-spinner rotation." },
    "elevation.base.0": { $type: "shadow", $value: [], $description: "No elevation." },
    "elevation.base.1": { $type: "shadow", $value: [
      { color: "{color.shadow.4}", offsetX: dimension(0), offsetY: dimension(1), blur: dimension(2), spread: dimension(0), inset: false },
      { color: "{color.shadow.6}", offsetX: dimension(0), offsetY: dimension(1), blur: dimension(1), spread: dimension(0), inset: false },
    ], $description: "Low elevation shadow." },
    "elevation.base.2": { $type: "shadow", $value: [
      { color: "{color.shadow.5}", offsetX: dimension(0), offsetY: dimension(2), blur: dimension(4), spread: dimension(0), inset: false },
      { color: "{color.shadow.8}", offsetX: dimension(0), offsetY: dimension(1), blur: dimension(2), spread: dimension(0), inset: false },
    ], $description: "Medium elevation shadow." },
    "elevation.base.3": { $type: "shadow", $value: [
      { color: "{color.shadow.6}", offsetX: dimension(0), offsetY: dimension(4), blur: dimension(8), spread: dimension(0), inset: false },
      { color: "{color.shadow.10}", offsetX: dimension(0), offsetY: dimension(2), blur: dimension(4), spread: dimension(0), inset: false },
    ], $description: "High elevation shadow." },
    "elevation.base.4": { $type: "shadow", $value: [
      { color: "{color.shadow.8}", offsetX: dimension(0), offsetY: dimension(8), blur: dimension(16), spread: dimension(0), inset: false },
      { color: "{color.shadow.12}", offsetX: dimension(0), offsetY: dimension(4), blur: dimension(8), spread: dimension(0), inset: false },
    ], $description: "Overlay elevation shadow." },
    "elevation.base.5": { $type: "shadow", $value: [
      { color: "{color.shadow.10}", offsetX: dimension(0), offsetY: dimension(12), blur: dimension(24), spread: dimension(0), inset: false },
      { color: "{color.shadow.14}", offsetX: dimension(0), offsetY: dimension(6), blur: dimension(12), spread: dimension(0), inset: false },
    ], $description: "Modal elevation shadow." },
    "elevation.none": { $type: "shadow", $value: "{elevation.base.0}", $description: "No elevation." },
    "elevation.low": { $type: "shadow", $value: "{elevation.base.1}", $description: "Low elevation." },
    "elevation.medium": { $type: "shadow", $value: "{elevation.base.2}", $description: "Medium elevation." },
    "elevation.high": { $type: "shadow", $value: "{elevation.base.3}", $description: "High elevation." },
    "elevation.overlay": { $type: "shadow", $value: "{elevation.base.4}", $description: "Overlay elevation." },
    "elevation.modal": { $type: "shadow", $value: "{elevation.base.5}", $description: "Modal elevation." },
    "z-index.raw.0": { $type: "number", $value: 0, $description: "Base stack level." },
    "z-index.raw.1": { $type: "number", $value: 10, $description: "Base stack level." },
    "z-index.raw.2": { $type: "number", $value: 20, $description: "Base stack level." },
    "z-index.raw.3": { $type: "number", $value: 30, $description: "Base stack level." },
    "z-index.raw.4": { $type: "number", $value: 40, $description: "Base stack level." },
    "z-index.raw.5": { $type: "number", $value: 50, $description: "Base stack level." },
    "z-index.raw.6": { $type: "number", $value: 60, $description: "Base stack level." },
    "z-index.raw.7": { $type: "number", $value: 70, $description: "Base stack level." },
    "z-index.base": { $type: "number", $value: "{z-index.raw.0}", $description: "Base stacking context." },
    "z-index.raised": { $type: "number", $value: "{z-index.raw.1}", $description: "Raised stacking context." },
    "z-index.sticky": { $type: "number", $value: "{z-index.raw.2}", $description: "Sticky stacking context." },
    "z-index.overlay": { $type: "number", $value: "{z-index.raw.3}", $description: "Overlay stacking context." },
    "z-index.modal": { $type: "number", $value: "{z-index.raw.4}", $description: "Modal stacking context." },
    "z-index.popover": { $type: "number", $value: "{z-index.raw.5}", $description: "Popover stacking context." },
    "z-index.toast": { $type: "number", $value: "{z-index.raw.6}", $description: "Toast stacking context." },
    "z-index.tooltip": { $type: "number", $value: "{z-index.raw.7}", $description: "Tooltip stacking context." },
  } as Record<string, TokenDefinition>,
  contrastPairs: [
    {
      id: "primary-rest",
      foreground: "color.text.on-primary",
      background: "color.fill.primary",
      usage: "normal-text",
    },
    {
      id: "primary-hover",
      foreground: "color.text.on-primary",
      background: "color.fill.primary-hover",
      usage: "normal-text",
    },
    {
      id: "primary-pressed",
      foreground: "color.text.on-primary",
      background: "color.fill.primary-pressed",
      usage: "normal-text",
    },
    {
      id: "secondary-rest",
      foreground: "color.text.on-secondary",
      background: "color.fill.secondary",
      usage: "normal-text",
    },
    {
      id: "secondary-hover",
      foreground: "color.text.on-secondary",
      background: "color.fill.secondary-hover",
      usage: "normal-text",
    },
    {
      id: "secondary-pressed",
      foreground: "color.text.on-secondary",
      background: "color.fill.secondary-pressed",
      usage: "normal-text",
    },
    {
      id: "tertiary-rest",
      foreground: "color.text.primary",
      background: "color.fill.tertiary",
      usage: "normal-text",
    },
    {
      id: "tertiary-hover",
      foreground: "color.text.primary",
      background: "color.fill.tertiary-hover",
      usage: "normal-text",
    },
    {
      id: "tertiary-pressed",
      foreground: "color.text.primary",
      background: "color.fill.tertiary-pressed",
      usage: "normal-text",
    },
    {
      id: "danger-rest",
      foreground: "color.text.on-danger",
      background: "color.fill.danger",
      usage: "normal-text",
    },
    {
      id: "danger-hover",
      foreground: "color.text.on-danger",
      background: "color.fill.danger-hover",
      usage: "normal-text",
    },
    {
      id: "danger-pressed",
      foreground: "color.text.on-danger",
      background: "color.fill.danger-pressed",
      usage: "normal-text",
    },
    {
      id: "surface-primary",
      foreground: "color.text.surface-primary",
      background: "color.fill.surface",
      usage: "normal-text",
    },
    {
      id: "surface-secondary",
      foreground: "color.text.surface-secondary",
      background: "color.fill.surface",
      usage: "normal-text",
    },
    {
      id: "success-subtle-primary",
      foreground: "color.text.success",
      background: "color.fill.success-subtle",
      usage: "normal-text",
    },
    {
      id: "success-subtle-secondary",
      foreground: "color.text.surface-secondary",
      background: "color.fill.success-subtle",
      usage: "normal-text",
    },
    {
      id: "danger-subtle-primary",
      foreground: "color.text.danger",
      background: "color.fill.danger-subtle",
      usage: "normal-text",
    },
    {
      id: "danger-subtle-secondary",
      foreground: "color.text.surface-secondary",
      background: "color.fill.danger-subtle",
      usage: "normal-text",
    },
  ],
});
