import { mkdirSync, readFileSync, readdirSync, renameSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Contract, Validated } from "../contracts/core.ts";
import { createContractRevision } from "../contracts/revision.ts";
import { fail } from "../contracts/validation.ts";
import { systemConfig, type SystemConfig } from "../system.config.ts";

export const GENERATOR_VERSION = "0.1.0";
export const GENERATED_MARKER = `@generated by ${systemConfig.displayName}. DO NOT EDIT.`;
export const REPOSITORY_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export type GeneratedOutput = Readonly<{ path: string; contents: string }>;
export type Artifact = GeneratedOutput;
export type Provenance = Readonly<{ systemId: string; packageScope: string; schemaVersion: number; contractId: string; contractRevision: string; generatorVersion: string }>;

export function stableData(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stableData);
  if (value !== null && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([key, child]) => [key, stableData(child)]));
  return value;
}

export function stableJson(value: unknown): string { return `${JSON.stringify(stableData(value), null, 2)}\n`; }
export function contractRevision(contract: Validated<Contract>): `sha256:${string}` { return createContractRevision(contract); }

export function provenance<T extends Contract>(contract: Validated<T>, config: SystemConfig = systemConfig): Provenance {
  return { systemId: config.systemId, packageScope: config.packageScope, schemaVersion: contract.schemaVersion, contractId: contract.id, contractRevision: createContractRevision(contract), generatorVersion: GENERATOR_VERSION };
}

export function generatedHeader(value: Validated<Contract> | Provenance, format: "css" | "ts" | "js" | "block" | "line" = "block", config: SystemConfig = systemConfig): string {
  const meta = "contractRevision" in value ? value : provenance(value, config);
  const rows = [GENERATED_MARKER, `systemId: ${meta.systemId}`, `packageScope: ${meta.packageScope}`, `contractId: ${meta.contractId}`, `schemaVersion: ${meta.schemaVersion}`, `contractRevision: ${meta.contractRevision}`, `generatorVersion: ${meta.generatorVersion}`];
  if (format === "line" || format === "ts" || format === "js") return `${rows.map((row) => `// ${row}`).join("\n")}\n\n`;
  return `/*\n${rows.map((row) => ` * ${row}`).join("\n")}\n */\n\n`;
}

export function cssVariable(packageScope: string, tokenName: string): string { return `--${packageScope.slice(1).replace(/[^a-z0-9-]+/gi, "-").toLowerCase()}-${tokenName.replace(/\./g, "-")}`; }
export function cssVariableName(tokenName: string, packageScope = systemConfig.packageScope): string { return cssVariable(packageScope, tokenName); }
export function tokenNameFromReference(reference: string): string { const prefix = "foundation.tokens."; if (!reference.startsWith(prefix)) throw new TypeError(`${reference} is not a foundation token reference`); return reference.slice(prefix.length); }
export function pascalCase(value: string): string { return value.split(/[^a-zA-Z0-9]+/).filter(Boolean).map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join(""); }
export function componentNameFromId(id: string): string { return pascalCase(id.slice(id.lastIndexOf(".") + 1)); }
export function validateCanonical<T extends Contract>(contract: Validated<T>, expectedId: string): void {
  const schemaVersion = expectedId === "foundation.tokens" ? 2 : 1;
  if (contract.id !== expectedId || contract.schemaVersion !== schemaVersion) {
    fail(`unsupported canonical contract: ${contract.id}@${contract.schemaVersion}`);
  }
  createContractRevision(contract);
}

function exists(path: string): boolean { try { statSync(path); return true; } catch { return false; } }
function filesUnder(root: string): string[] { if (!exists(root)) return []; return readdirSync(root, { withFileTypes: true }).flatMap((entry) => { const path = join(root, entry.name); return entry.isDirectory() ? filesUnder(path) : [path]; }); }

export function compareArtifacts(rootDir: string, outputs: readonly GeneratedOutput[]): string[] {
  const expected = new Map(outputs.map((output) => [resolve(rootDir, output.path), output.contents]));
  const scanRoots = [join(rootDir, "foundations", "tokens"), join(rootDir, "foundations", "assets"), join(rootDir, "components")];
  const paths = new Set([...expected.keys(), ...scanRoots.flatMap(filesUnder).filter((path) => { try { return readFileSync(path, "utf8").includes(GENERATED_MARKER); } catch { return false; } })]);
  return [...paths].sort().flatMap((path) => { const expectedContents = expected.get(path); if (expectedContents === undefined) return [`STALE ${relative(rootDir, path)}`]; if (!exists(path)) return [`MISSING ${relative(rootDir, path)}`]; return readFileSync(path, "utf8") === expectedContents ? [] : [`DIFF ${relative(rootDir, path)}`]; });
}

export function writeArtifacts(rootDir: string, outputs: readonly GeneratedOutput[], check = false, overwrite = false): void {
  const root = resolve(rootDir);
  const targets = outputs.map((output) => {
    const target = resolve(root, output.path);
    if (relative(root, target).startsWith("..")) fail(`artifact escapes root: ${output.path}`);
    return target;
  });
  const problems = compareArtifacts(root, outputs);
  if (check) { if (problems.length) throw new Error(problems.join("\n")); return; }
  const protectedDiffs = problems.filter((problem) => problem.startsWith("DIFF "));
  if (!overwrite && protectedDiffs.length) throw new Error(`Refusing to overwrite modified generated artifacts without explicit --force:\n${protectedDiffs.join("\n")}`);
  for (const [index, output] of outputs.entries()) {
    const target = targets[index];
    mkdirSync(dirname(target), { recursive: true });
    const temporary = `${target}.tmp-${process.pid}-${index}`;
    try { writeFileSync(temporary, output.contents, { encoding: "utf8", flag: "wx", mode: 0o644 }); renameSync(temporary, target); } catch (error) { try { unlinkSync(temporary); } catch { /* preserve original write error */ } throw error; }
  }
}

export function applyGeneratedOutputs(outputs: readonly GeneratedOutput[], check: boolean, overwrite = false): void { writeArtifacts(REPOSITORY_ROOT, outputs, check, overwrite); }
